### ISSUE TITLE
index >= CMT_SUMMARY_QUANTILE_ELEMENT_LIMIT

### ISSUE THREAD

**Issue by nokute78** [fluent/cmetrics#167]
https://github.com/fluent/fluent-bit/issues/6322

Fluent-bit [master](https://github.com/fluent/fluent-bit/tree/01d6656b71ed68cc249a7e86d47c94f3a77db9b5) reaches following limit and returned error.
https://github.com/fluent/fluent-bit/blob/v2.0.3/lib/cmetrics/src/cmt_decode_msgpack.c#L446
```
[2022/11/03 09:28:07] [error] [output:stdout:stdout.0] could not process metrics payload 
```

## How to reproduce 

1. Run [prometheus](https://github.com/prometheus/prometheus/releases/tag/v2.39.1)
2. Run Fluent-bit

## Fluent-bit configuration

```
[INPUT]
    name prometheus_scrape
    host 0.0.0.0
    port 9090
    tag prometheus
    metrics_path /metrics?format=prometheus
    scrape_interval 5s

[OUTPUT]
    Name stdout
```

**Comment by edsiper** [comment]
fixed in #168
