### ISSUE TITLE
Add "const" modifier to "char *" parameters that don't modify it

### ISSUE THREAD

**Issue by tarruda** [fluent/cmetrics#65]
Functions that create/modify metrics don't modify their `char *` parameters, so it would be good to add `const` modifier to let the compiler know callers don't expect it to be modified.

**Comment by edsiper** [comment]
used to be a practice, but at the moment that might trigger lot of warnings in Fluent Bit caller

**Comment by fredrik-jansson-se** [comment]
Integrating with cmetrics from rust (bindgen), and it would had been great with `const` modifers. As of now I have to jump through hoops to pass c-strings to functions that could take `const char*`.

**Comment by edsiper** [comment]
closing as not a go for now, unless we have a big use case to solve.
